version: '3'
services:
    poke-api:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - poke
        depends_on:
            - poke-db
    poke-db:
        image: 'postgres'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_DB: '${DB_DATABASE}'
            PGDATA: /data/postgres
        volumes:
            - 'poke-db:/var/lib/postgresql'
        env_file:
            - .env
        networks:
            - poke
        # healthcheck:
        #     test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
        #     interval: 10s
        #     timeout: 3s
        #     retries: 3
networks:
    poke:
        driver: bridge
volumes:
    poke-db:
        driver: local
